/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonAddToCart: typeof import('./components/ButtonAddToCart.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    CartItem: typeof import('./components/CartItem.vue')['default']
    DialogOrder: typeof import('./components/DialogOrder.vue')['default']
    DialogSearch: typeof import('./components/DialogSearch.vue')['default']
    DialogSuccess: typeof import('./components/DialogSuccess.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    Footer: typeof import('./components/Footer.vue')['default']
    Input: typeof import('./components/Input.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    MyReviewItem: typeof import('./components/MyReviewItem.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    OrderHistory: typeof import('./components/OrderHistory.vue')['default']
    OrderHistoryItem: typeof import('./components/OrderHistoryItem.vue')['default']
    OrderStatusCard: typeof import('./components/OrderStatusCard.vue')['default']
    Products: typeof import('./components/Products.vue')['default']
    ProfileItem: typeof import('./components/ProfileItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultItem: typeof import('./components/SearchResultItem.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    Stepper: typeof import('./components/Stepper.vue')['default']
    UserInfoItem: typeof import('./components/UserInfoItem.vue')['default']
  }
}
